var word_explanations = {
  "admin": "Admin is a feature in every Among Us map that allows players to view player locations",
  "align": "Align Engine Output and Align Telescope are tasks in the Among Us maps The Skeld and Polus, respectively",
  "among": "\"Among\" is the first word in the title of the game Among Us.",
  "angel": "The Guardian Angel is a role in Among Us that allows a player to protect a Crewmate from being killed",
  "avert": "Avert Crash Course is a sabotage in the Among Us map The Airship",
  "batty": "Batty is a hat cosmetic in Among Us",
  "beans": "Beans are a type of in-game currency in Among Us",
  "beard": "A Beard is a visor cosmetic in Among Us",
  "black": "Black is one of the colors players can select for their character in Among Us",
  "bling": "Bling Bling is a skin cosmetic in Among Us",
  "brown": "Brown is one of the colors players can select for their character in Among Us",
  "candy": "Candy Time is a nameplate cosmetic in Among Us",
  "cargo": "The Cargo Bay is a room in the Among Us map The Airship",
  "chart": "Chart Course is a task in the Among Us maps The Skeld, MIRA HQ, and Polus",
  "chute": "Empty Chute is a task in the Among Us map The Skeld",
  "clank": "Clank pet is a PlayStation-exclusive pet cosmetic in Among Us",
  "clark": "Jake Clark is an animator who worked on Among Us",
  "claus": "Claus, Mrs. Claus is a skin cosmetic in Among Us",
  "clean": "Four separate Among Us tasks involve cleaning",
  "clear": "Clear Asteroids is a task in the Among Us maps The Skeld, MIRA HQ, and Polus",
  "close": "In Among Us, doors can temporarily close to prevent players from traversing various map areas",
  "clown": "In Among Us, Clown Town is a hat cosmetic and Crewbo the Clown is a skin cosmetic",
  "color": "In Among Us, players can change the color of their character",
  "comms": "Comms Sabotaged is a sabotage in all four Among Us maps",
  "coral": "Coral is one of the colors players can select for their character in Among Us",
  "crash": "Avert Crash Course is a sabotage in the Among Us map The Airship",
  "daisy": "Daisy Me Rollin' is a hat cosmetic in Among Us",
  "dawko": "Dawko is an online content creator who frequently played Among Us",
  "doggy": "Doggy is a pet cosmetic in Among Us",
  "doned": "Done D is a hat cosmetic in Among Us",
  "doors": "In Among Us, doors are objects that can temporarily close and prevent players from traversing various map areas",
  "dream": "Dream is an online content creator who frequently played Among Us",
  "dress": "Dress Mannequin is a task in the Among Us map The Airship",
  "drill": "In Among Us, Repair Drill is a task in the map Polus, and Drill is a hat cosmetic",
  "eject": "In Among Us, a player can be ejected if a majority of players vote for their ejection during a meeting",
  "empty": "Empty Chute and Empty Garbage are tasks in various Among Us maps",
  "enter": "Enter Id Code is a task in the Among Us maps MIRA HQ and The Airship",
  "erose": "E. Rose is a pet cosmetic in Among Us",
  "fairy": "Fairy Flutters is a hat cosmetic in Among Us",
  "games": "Among Us is a game",
  "ghost": "The ghost is a role in Among Us that players adopt after they die",
  "glove": "You Glove to See it is a hat cosmetic in Among Us",
  "green": "Green is one of the colors players can select for their character in Among Us",
  "henry": "In 2021, Among Us released the map The Airship inspired the Henry Stickmin game Infiltrating the Airship, and Henry Stickmin is a pet cosmetic",
  "indie": "Among Us is an indie game",
  "inner": "Among Us was developed and published by the video game development studio InnerSloth LLC",
  "jayce": "Several Among Us cosmetic items are inspired by Jayce, a character from the show Arcane",
  "jerma": "Jerma985 is an online content creator who frequently played Among Us and the likeness of the \"When the Imposter is Sus\" meme",
  "katie": "Cool Katie is a hat cosmetic in Among Us",
  "kicks": "In Among Us, players can be kicked from a game",
  "kills": "In Among Us, imposters kill crewmates",
  "knife": "Knives feature prominently in Among Us kill animations and fanart",
  "light": "Fix Lights is a sabotage in all four Among Us maps",
  "lobby": "In Among Us, players spawn in a lobby before the game begins",
  "mafia": "Among Us was inspired by the party game Mafia",
  "miner": "Miner Setback is a hat cosmetic in Among Us",
  "mogus": ""Mogus\" is a contraction for \"amogus,\" which itself is a portmanteau for \"Among Us\"",
  "moist": "MoistCr1TiKaL is an online content creator who frequently played Among Us",
  "muffs": "Muffs is a hat cosmetic in Among Us",
  "nogla": "Nogla is an online content creator who frequently played Among Us",
  "olive": "Olive is an unused Among Us color",
  "party": "P Hat is a hat cosmetic in Among Us that resembles a party hat",
  "plant": "In Among Us, Water Plants is a task in the map MIRA HQ and Planted is a hat cosmetic",
  "plays": "Among Us is a game that can be played",
  "photo": "Develop Photos is a task in the Among Us map The Airship",
  "polus": "Polus is a map in Among Us",
  "power": "Divert Power is a task in the Among Us maps The Skeld, MIRA HQ, and The Airship",
  "prime": "Prime Shields is a task in the Among Us maps The Skeld and MIRA HQ",
  "reset": "Reset Breakers is a task in the Among Us map The Airship",
  "rifle": "Put Away Rifles is a task in the Among Us map The Airship",
  "robot": "Ro-Bot is a pet cosmetic in Among Us",
  "roles": "Roles are a game mechanic in Among Us that give players different goals and abilities",
  "rooms": "Among Us maps feature numerous rooms",
  "scoop": "Chocolate Scoop is a hat cosmetic in Among Us",
  "shift": "Shift is an ability in Among Us that can be used by Shapeshifters",
  "ships": "The Among Us maps The Skeld and The Airship are ships",
  "short": "In Among Us, short is an option for the kill distance and Short Tasks is a type of task",
  "skeld": "The Skeld is a map in Among Us",
  "skins": "Skins are a type of wearable cosmetic in Among Us",
  "sloth": "Among Us was developed and published by the video game development studio InnerSloth LLC",
  "snowy": "Snowy Lands is a nameplate cosmetic in Among Us",
  "space": "In Among Us, space feature prominently in the artistic design and the map The Skeld is set in space",
  "specs": "Spectacles and Tiny Specs are visor cosmetics in Among Us",
  "speed": "Player Speed is a setting in Among Us",
  "squig": "Squig is a pet cosmetic in Among Us",
  "stars": "In Among Us, stars feature prominently in the artistic design and Stars are a type of in-game currency",
  "start": "To begin a game of Among Us, one must press the Start button",
  "store": "Store Artifacts is a task in the Among Us map Polus",
  "sussy": "\"Sussy\" is a contraction for \"suspicious,\" a word commonly used to refer to Imposters in Among Us",
  "swipe": "Swipe Card is a task in the Among Us maps The Skeld and Polus",
  "tapes": "Rewind Tapes is a task in the Among Us map The Airship",
  "tasks": "Tasks are objectives completed by Crewmates in Among Us",
  "times": "Discussion Time, Voting Times, and Max Time in Vents are settings in Among Us",
  "toast": "Disguised Toast is an online content creator who frequently played Among Us",
  "torin": "Torin Freimiller is a backend programmer who worked on Among Us",
  "towel": "Pick Up Towels is a task in the Among Us map The Airship",
  "treat": "The Treat Cosmicube is a Halloween-themed Cosmicube in Among Us",
  "trees": "Monitor Tree is a task in the Among Us map Polus, and Trees is a nameplate cosmetic",
  "trick": "The Trick Cosmicube is a Halloween-themed Cosmicube in Among Us",
  "unity": "Among Us runs on the game engine Unity",
  "vault": "The Vault Above is a nameplate cosmetic in Among Us",
  "vents": "Vents are a method of transportation in Among Us maps that can be used by Imposters or Engineers",
  "visor": "Visors are part of the character design in Among Us",
  "votes": "In Among Us, players can vote to either eject another player or to skip",
  "water": "Water Plants and Replace Water Jug are tasks in the Among Us maps MIRA HQ and Polus, respectively",
  "white": "White is one of the colors players can select for their character in Among Us",
  "wires": "Fix Wiring is a task in all four Among Us maps",
  "witch": "In Among Us, Witch One is a hat cosmetic and Whimsy Witch is a skin cosmetic",
  "woods": "Spooky Woods is a nameplate cosmetic in Among Us"
};
